<Project>

  <!-- UseAlternatePack default to false. Store 'true' for any value MSBuild compares equal to it, such as 'yes'. -->
  <PropertyGroup Condition="'$(UseAlternatePack)' == 'true'">
    <UseAlternatePack>true</UseAlternatePack>
  </PropertyGroup>
  <PropertyGroup Condition="'$(UseAlternatePack)' != 'true'">
    <UseAlternatePack>false</UseAlternatePack>
  </PropertyGroup>

  <!-- Disable functionality provided by the NuGetPack module when using alternate pack. -->
  <PropertyGroup Condition="$(UseAlternatePack)">
    <IncludeNuGetPackSupport>false</IncludeNuGetPackSupport>
  </PropertyGroup>

  <Import Project="BeforeModules.Core.targets"
          Condition="$(UseAlternatePack)" />

</Project>
