<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(SourceGeneratorsTfm)</TargetFramework>
    <CLSCompliant>false</CLSCompliant>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Buildvana.Sdk.SourceGenerators.Tests" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="AnalyzerReleases.Shipped.md" />
    <AdditionalFiles Include="AnalyzerReleases.Unshipped.md" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" PrivateAssets="all" />
    <PackageReference Include="PolyKit.Embedded" PrivateAssets="all" />
  </ItemGroup>

</Project>
