// Copyright (C) Tenacom and Contributors. Licensed under the MIT license.
// See the LICENSE file in the project root for full license information.

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using Buildvana.Sdk.SourceGenerators.Internal;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;

namespace Buildvana.Sdk.SourceGenerators;

/// <summary>
/// Generates a <c>ThisAssembly</c> static class containing constants defined via <c>ThisAssemblyConstant</c> items.
/// The constants are read from a file written by the <c>WriteThisAssemblyConstantsFile</c> task
/// and exposed to the generator as an <c>AdditionalFiles</c> item whose <c>BV_ItemType</c> metadata
/// is <c>ThisAssemblyConstants</c>. C# projects only.
/// </summary>
[Generator(LanguageNames.CSharp)]
public class ThisAssemblyClassGenerator : IIncrementalGenerator
{
    private const string DefaultClassName = "ThisAssembly";

    private static readonly DiagnosticDescriptor InvalidConstantValueDescriptor = new(
        "BVSDK2301",
        "Invalid ThisAssembly constant value",
        "Constant '{0}' has invalid value '{1}'",
        "Buildvana.Sdk",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var constantsTextsProvider = context.AdditionalTextsProvider
                                            .Combine(context.AnalyzerConfigOptionsProvider)
                                            .Where(static pair => IsConstantsFile(pair.Right.GetOptions(pair.Left)))
                                            .Select(static (pair, cancellationToken) => pair.Left.GetText(cancellationToken)?.ToString() ?? string.Empty)
                                            .Collect();

        var optionsProvider = context.AnalyzerConfigOptionsProvider
                                     .Select(static (p, _)
                                          => (ClassName: p.GetMSBuildProperty("ThisAssemblyClassName") ?? DefaultClassName,
                                              Namespace: p.GetMSBuildProperty("ThisAssemblyClassNamespace")));

        var finalProvider = constantsTextsProvider.Combine(optionsProvider);
        context.RegisterSourceOutput(finalProvider, static (spc, data) =>
        {
            var (constantsTexts, options) = data;
            GenerateThisAssemblyClass(spc, constantsTexts, options.ClassName, options.Namespace);
        });
    }

    private static void GenerateThisAssemblyClass(
        SourceProductionContext context,
        ImmutableArray<string> constantsTexts,
        string className,
        string? namespaceName)
    {
        if (constantsTexts.IsEmpty)
        {
            return;
        }

        if (!TryParseConstants(context, constantsTexts, out var constants) || constants.Count == 0)
        {
            return;
        }

        var sb = new StringBuilder();
        _ = sb.AppendLine("// <auto-generated/>")
              .AppendLine()
              .AppendLine("#nullable enable")
              .AppendLine();

        var indent = string.Empty;
        if (!string.IsNullOrEmpty(namespaceName))
        {
            _ = sb.AppendLine($"namespace {namespaceName}")
                  .AppendLine("{");
            indent = "    ";
        }

        _ = sb.AppendLine($"{indent}[global::System.Runtime.CompilerServices.CompilerGenerated]")
              .AppendLine($"{indent}[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]")
              .AppendLine($"{indent}internal static partial class {className}")
              .AppendLine($"{indent}{{");

        foreach (var (name, value) in constants)
        {
            _ = sb.AppendLine($"{indent}    public const {GetTypeKeyword(value)} {name} = {GetLiteral(value)};");
        }

        _ = sb.AppendLine($"{indent}}}");
        if (indent.Length > 0)
        {
            _ = sb.AppendLine("}");
        }

        context.AddSource("BV_ThisAssembly", sb.ToString());
    }

    private static bool TryParseConstants(
        SourceProductionContext context,
        ImmutableArray<string> constantsTexts,
        out List<(string Name, object? Value)> constants)
    {
        constants = [];
        var success = true;
        foreach (var text in constantsTexts)
        {
            foreach (var line in text.Split('\n'))
            {
                var trimmedLine = line.TrimEnd('\r');
                if (trimmedLine.Length == 0)
                {
                    continue;
                }

                var equalsPos = trimmedLine.IndexOf('=');
                var name = Uri.UnescapeDataString(equalsPos < 0 ? trimmedLine : trimmedLine.Substring(0, equalsPos));
                var rawValue = equalsPos < 0 ? string.Empty : Uri.UnescapeDataString(trimmedLine.Substring(equalsPos + 1));
                if (!ConstantValueParser.TryParse(rawValue, out var value))
                {
                    context.ReportDiagnostic(Diagnostic.Create(InvalidConstantValueDescriptor, Location.None, name, rawValue));
                    success = false;
                    continue;
                }

                constants.Add((name, value));
            }
        }

        return success;
    }

    private static bool IsConstantsFile(AnalyzerConfigOptions options)
        => options.TryGetValue("build_metadata.AdditionalFiles.BV_ItemType", out var itemType)
            && itemType == "ThisAssemblyConstants";

    // NOTE: All supported types must be listed (check ConstantValueParser.AllowedTypes).
    private static string GetTypeKeyword(object? value)
        => value switch {
            null => "string?",
            byte => "byte",
            short => "short",
            int => "int",
            long => "long",
            bool => "bool",
            string => "string",
            _ => throw new ArgumentException("Unsupported type for a constant.", nameof(value)),
        };

    // NOTE: All supported types must be listed (check ConstantValueParser.AllowedTypes).
    private static string GetLiteral(object? value)
        => value switch {
            null => "null",
            byte byteValue => byteValue.ToString(CultureInfo.InvariantCulture),
            short shortValue => shortValue.ToString(CultureInfo.InvariantCulture),
            int intValue => intValue.ToString(CultureInfo.InvariantCulture),
            long longValue => longValue.ToString(CultureInfo.InvariantCulture) + "L",
            bool boolValue => boolValue ? "true" : "false",
            string stringValue => GetStringLiteral(stringValue),
            _ => throw new ArgumentException("Unsupported type for a constant.", nameof(value)),
        };

    private static string GetStringLiteral(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        _ = sb.Append('"');
        foreach (var c in value)
        {
            _ = c switch {
                '"' => sb.Append("\\\""),
                '\\' => sb.Append("\\\\"),
                '\n' => sb.Append("\\n"),
                '\r' => sb.Append("\\r"),
                '\t' => sb.Append("\\t"),
                '\u2028' or '\u2029' => AppendEscaped(sb, c), // line separators end a line in C# but are not covered by char.IsControl
                _ => char.IsControl(c) ? AppendEscaped(sb, c) : sb.Append(c),
            };
        }

        return sb.Append('"').ToString();

        static StringBuilder AppendEscaped(StringBuilder sb, char c)
            => sb.Append("\\u").Append(((int)c).ToString("x4", CultureInfo.InvariantCulture));
    }
}
