'area:code':
 - changed-files:
    - any-glob-to-any-file:
      - 'src/**/*'
      - 'tests/**/*'

'area:build':
 - changed-files:
    - any-glob-to-any-file:
      - '.buildvana/**/*'
      - 'tools/**/*'
      - '*.sln'
      - '*.slnx'
      - '**/*.props'
      - '**/*.targets'
      - VERSION

'area:style':
 - changed-files:
    - any-glob-to-any-file:
      - '**/.editorconfig'
      - '**/.globalconfig'
      - '**/stylecop.json'
      - '**/*.DotSettings'

'area:repo':
 - changed-files:
    - any-glob-to-any-file:
      - '.github/*.yml'
      - '.github/**/*.md'
      - CODEOWNERS
      - '.github/CODEOWNERS'

'area:ci':
 - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**/*'

'area:deps':
 - changed-files:
    - any-glob-to-any-file:
      - '**/Directory.Packages.props'
      - global.json
      - .config/dotnet-tools.json

'area:docs':
 - changed-files:
    - any-glob-to-any-file:
      - 'docs/**/*'
      - '.all-contributorsrc'
      - '**/CHANGELOG.md'
      - '**/LICENSE'
      - '**/NuGet-README.md'
      - '**/README.md'
      - '**/THIRD-PARTY-GRAPHICS.md'
      - '**/THIRD-PARTY-NOTICES.md'
