<Project>

  <!-- Common build options for test projects -->
  <PropertyGroup Condition="'$(IsTestingPlatformApplication)' == 'true'">

    <!--
        Test assemblies are not going to interoperate much.
        Besides, the type names used in test projects are not apt to cause ambiguities.
        Therefore there is no need for a root namespace: let's save ourselves some declarations.
    -->
    <RootNamespace />

    <!-- No need for public API analyzers -->
    <UsePublicApiAnalyzers>false</UsePublicApiAnalyzers>

  </PropertyGroup>

  <!-- Hide test result files in Visual Studio -->
  <ItemGroup Condition="'$(IsTestingPlatformApplication)' == 'true'">
    <None Remove="TestResults\**" />
  </ItemGroup>

</Project>
