// Copyright (C) Tenacom and Contributors. Licensed under the MIT license.
// See the LICENSE file in the project root for full license information.

using Buildvana.Sdk.SourceGenerators;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

internal sealed class AdditionalAssemblyInfoGeneratorTests
{
    [Test]
    public async Task BothProperties_GenerateBothAttributes()
    {
        var (source, outputCompilation) = RunGenerator(clsCompliant: "true", comVisible: "false");
        await Assert.That(source).Contains("[assembly:System.CLSCompliant(true)]");
        await Assert.That(source).Contains("[assembly:System.Runtime.InteropServices.ComVisible(false)]");
        await TestCompilation.AssertHasNoErrors(outputCompilation).ConfigureAwait(false);
    }

    [Test]
    public async Task MissingProperty_GeneratesNoAttributeForIt()
    {
        var (source, outputCompilation) = RunGenerator(clsCompliant: null, comVisible: "true");
        await Assert.That(source).DoesNotContain("CLSCompliant");
        await Assert.That(source).Contains("[assembly:System.Runtime.InteropServices.ComVisible(true)]");
        await TestCompilation.AssertHasNoErrors(outputCompilation).ConfigureAwait(false);
    }

    [Test]
    public async Task NoProperties_GenerateHeaderOnly()
    {
        var (source, outputCompilation) = RunGenerator(clsCompliant: null, comVisible: null);
        await Assert.That(source.TrimEnd()).IsEqualTo("// <auto-generated/>");
        await TestCompilation.AssertHasNoErrors(outputCompilation).ConfigureAwait(false);
    }

    private static (string Source, Compilation OutputCompilation) RunGenerator(string? clsCompliant, string? comVisible)
    {
        var globalOptions = new Dictionary<string, string>();
        if (clsCompliant is not null)
        {
            globalOptions["build_property.CLSCompliant"] = clsCompliant;
        }

        if (comVisible is not null)
        {
            globalOptions["build_property.ComVisible"] = comVisible;
        }

        var optionsProvider = new TestAnalyzerConfigOptionsProvider(
            globalOptions,
            new Dictionary<string, IReadOnlyDictionary<string, string>>());
        var driver = CSharpGeneratorDriver.Create(
            [new AdditionalAssemblyInfoGenerator().AsSourceGenerator()],
            optionsProvider: optionsProvider);
        var compilation = TestCompilation.Create();
        var runResult = driver.RunGeneratorsAndUpdateCompilation(compilation, out var outputCompilation, out _).GetRunResult();
        return (runResult.GeneratedTrees.Single().ToString(), outputCompilation);
    }
}
