<Project>

  <PropertyGroup>
    <!-- Store 'true' for any value MSBuild compares equal to it, such as 'yes'. -->
    <BV_UseSdkCodeGenerators Condition="'$(BV_UseSdkCodeGenerators)' == 'true'">true</BV_UseSdkCodeGenerators>
    <BV_UseSdkCodeGenerators Condition="'$(BV_UseSdkCodeGenerators)' != 'true'">false</BV_UseSdkCodeGenerators>
  </PropertyGroup>

  <Import Project="$(MSBuildThisFileDirectory)AfterModules.Core.targets"
          Condition="$(BV_UseSdkCodeGenerators)" />

</Project>
