// Copyright (C) Tenacom and Contributors. Licensed under the MIT license.
// See the LICENSE file in the project root for full license information.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace Buildvana.Core.Configuration;

/// <summary>
/// Generates the worked example of a Buildvana configuration file: every setting, introduced by its
/// description and carrying an illustrative value.
/// </summary>
/// <remarks>
/// <para>The example is walked off the generated schema rather than the wire model, because the schema has
/// already resolved descriptions, defaults, examples, and member-name constraints. Nothing here reflects.</para>
/// <para>No comment in the generated file holds JSON. A commented-out member is parsed by nothing, so nothing
/// can tell a stale one from a current one; the example states every setting instead of commenting any out.</para>
/// </remarks>
public static class BuildvanaJsonConfigExample
{
    // A description takes one comment line up to this many characters, counting neither the indentation nor
    // the "// " before it. The limit is generous on purpose: a second line carrying three words reads worse
    // than one long line.
    private const int SingleLineLimit = 80;

    // Once a second line is unavoidable, the text wraps greedily at this narrower width.
    private const int WrappedLineLimit = 72;

    // A description is a one-liner, or a two-liner where it must be. A third line is documentation, which
    // belongs in docs/BuildvanaToolConfiguration.md rather than in an editor tooltip.
    private const int MaxDescriptionLines = 2;

    private const string IndentUnit = "  ";

    private const string Header = """
        // Buildvana configuration: every setting, with its description and an
        // example or default value.
        //
        // Generated by tools/generate-config-example.cs. Do not edit.
        //
        // Nothing reads this file. Buildvana looks only for buildvana.json and
        // buildvana.jsonc, so copy the settings you want into one of those.

        """;

    // The default encoder escapes characters that are only dangerous in HTML, turning a regular expression
    // into a wall of \u sequences. This file is read by people and copied into a configuration file, so a
    // value has to appear as it will be written there.
    private static readonly JsonSerializerOptions ValueOptions = new()
    {
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
    };

    /// <summary>
    /// Generates the worked example.
    /// </summary>
    /// <returns>The file text, using LF line endings and a trailing newline.</returns>
    /// <exception cref="InvalidOperationException">
    /// <para>A schema property states no value the example could carry, or states an example beside members
    /// or member names of its own, or a keyed object states no example member name, or a description does
    /// not fit the comment layer.</para>
    /// </exception>
    public static string Generate()
    {
        var root = (JsonObject)BuildvanaJsonConfigSchema.GenerateNode();
        var text = new StringBuilder(Header.ReplaceLineEndings("\n"));
        WriteMembers(text, CollectMembers(root), root, path: string.Empty, depth: 0);
        return text.Append('\n').ToString();
    }

    /// <summary>
    /// Reports why a description does not fit the comment layer of a generated file.
    /// </summary>
    /// <param name="description">The description to measure.</param>
    /// <returns>A phrase naming the problem, or <see langword="null"/> when the description fits.</returns>
    /// <remarks>
    /// <para>Counting lines is not enough: a word longer than the wrapped limit — a URL, say — produces a
    /// line the wrap cannot shorten, and the count stays at one.</para>
    /// </remarks>
    internal static string? DescriptionProblem(string description)
    {
        var lines = WrapDescription(description);
        if (lines.Count > MaxDescriptionLines)
        {
            return $"needs {lines.Count} comment lines, past the {MaxDescriptionLines} a description gets";
        }

        var limit = lines.Count == 1 ? SingleLineLimit : WrappedLineLimit;

        return lines.FirstOrDefault(line => line.Length > limit) is { } overrun
            ? $"holds a {overrun.Length}-character line, past the {limit} a comment line gets"
            : null;
    }

    /// <summary>
    /// Splits a description into the comment lines that carry it.
    /// </summary>
    /// <param name="description">The description to wrap.</param>
    /// <returns>One line when the description fits <c>80</c> characters, a greedy wrap at <c>72</c>
    /// otherwise.</returns>
    /// <remarks>
    /// <para>The two limits differ on purpose. A single line is allowed to run longer, so that a description
    /// just past the narrower limit does not spill a handful of words onto a line of its own.</para>
    /// </remarks>
    internal static IReadOnlyList<string> WrapDescription(string description)
    {
        ArgumentNullException.ThrowIfNull(description);
        if (description.Length <= SingleLineLimit)
        {
            return [description];
        }

        List<string> lines = [];
        var line = new StringBuilder();
        foreach (var word in description.Split(' '))
        {
            if (line.Length == 0)
            {
                _ = line.Append(word);
            }
            else if (line.Length + 1 + word.Length <= WrappedLineLimit)
            {
                _ = line.Append(' ').Append(word);
            }
            else
            {
                lines.Add(line.ToString());
                _ = line.Clear().Append(word);
            }
        }

        if (line.Length > 0)
        {
            lines.Add(line.ToString());
        }

        return lines;
    }

    /// <summary>
    /// Follows a document-local JSON pointer to the subschema it names.
    /// </summary>
    /// <param name="schema">The schema node carrying the <c>$ref</c> keyword.</param>
    /// <param name="root">The schema document the pointer is relative to.</param>
    /// <param name="path">The setting the reference was found at, for the error message.</param>
    /// <returns>The subschema the pointer names.</returns>
    /// <exception cref="InvalidOperationException">The pointer does not resolve.</exception>
    /// <remarks>
    /// <para>A document-local pointer is the only kind the exporter emits, for a member type that occurs more
    /// than once. Internal, because the tests navigate the same schema and must see through the same
    /// pointers.</para>
    /// </remarks>
    internal static JsonObject ResolveReference(JsonObject schema, JsonObject root, string path)
    {
        ArgumentNullException.ThrowIfNull(schema);
        ArgumentNullException.ThrowIfNull(root);

        var pointer = schema["$ref"]!.GetValue<string>();
        JsonNode node = root;
        foreach (var token in pointer.Split('/').Skip(1))
        {
            var name = token.Replace("~1", "/", StringComparison.Ordinal).Replace("~0", "~", StringComparison.Ordinal);
            node = node[name]
                ?? throw new InvalidOperationException(
                    $"The reference '{pointer}' at '{path}' does not resolve within the schema.");
        }

        return (JsonObject)node;
    }

    // Writes an object body: every member preceded by its own description, and separated from the next by a
    // blank line. The opening brace lands where the caller left the cursor; the closing one gets its own line.
    private static void WriteMembers(
        StringBuilder text,
        List<(string Name, JsonObject Schema)> members,
        JsonObject root,
        string path,
        int depth)
    {
        _ = text.Append("{\n");
        for (var i = 0; i < members.Count; i++)
        {
            if (i > 0)
            {
                _ = text.Append('\n');
            }

            var (name, schema) = members[i];
            WriteDescription(text, schema, depth + 1);
            _ = text.Append(Indentation(depth + 1)).Append(FormatString(name)).Append(": ");
            WriteValue(text, schema, root, Extend(path, name), depth + 1);

            // The last member carries a comma too, so that adding one after it touches a single line. Every
            // reader of a configuration file accepts a trailing comma, this file's own loader included.
            _ = text.Append(",\n");
        }

        _ = text.Append(Indentation(depth)).Append('}');
    }

    private static void WriteDescription(StringBuilder text, JsonObject schema, int depth)
    {
        if (schema["description"]?.GetValue<string>() is not { } description)
        {
            return;
        }

        if (DescriptionProblem(description) is { } problem)
        {
            throw new InvalidOperationException(
                $"The description \"{description}\" {problem}. A description names a setting; anything "
                + "longer is documentation, and belongs in the reference document.");
        }

        foreach (var line in WrapDescription(description))
        {
            _ = text.Append(Indentation(depth)).Append("// ").Append(line).Append('\n');
        }
    }

    // Writes the value of one member, in the order that puts the most deliberate answer first.
    private static void WriteValue(StringBuilder text, JsonObject schema, JsonObject root, string path, int depth)
    {
        // An example is chosen to illustrate, so it outranks everything below. A setting is annotated only
        // where its default is absent or unhelpful, so in practice the two never compete.
        if (schema["examples"] is JsonArray { Count: > 0 } examples)
        {
            // An example on a section would stand in for the section, dropping every member and every
            // nested description with it. Nothing else would notice, and the loss would reach the
            // committed file, so refuse the annotation here. A keyed object is a section too: it declares
            // member names through propertyNames, which a plain dictionary does not, and a dictionary is
            // the one object an example does illustrate whole.
            if (schema["properties"] is JsonObject || schema["propertyNames"] is JsonObject)
            {
                throw new InvalidOperationException(
                    $"The setting '{path}' states an example, and declares members or member names of its "
                    + "own. The example would replace them, and every description inside. Annotate the "
                    + "members instead.");
            }

            _ = text.Append(FormatValue(examples[0]));
            return;
        }

        if (schema["properties"] is JsonObject)
        {
            WriteMembers(text, CollectMembers(schema), root, path, depth);
            return;
        }

        // A keyed object's member names are data, so the schema constrains them through propertyNames, which
        // is also where the example of a member name lives.
        if (schema["propertyNames"] is JsonObject propertyNames)
        {
            WriteKeyedObject(text, schema, propertyNames, root, path, depth);
            return;
        }

        if (schema["default"] is { } defaultValue)
        {
            _ = text.Append(FormatValue(defaultValue));
            return;
        }

        // A "$ref" is the exporter deduplicating a member type that occurs more than once. Nothing local
        // answers, so the shared subschema it points at is where the answer has to be.
        if (schema["$ref"] is not null)
        {
            WriteValue(text, ResolveReference(schema, root, path), root, path, depth);
            return;
        }

        _ = text.Append(EmptyContainer(schema, path));
    }

    // The members a schema declares, in schema order, minus the ones it forbids. A subschema that is not an
    // object is a Boolean schema: "caption": false, the member name a package group travels under, which no
    // value object may restate.
    private static List<(string Name, JsonObject Schema)> CollectMembers(JsonObject schema)
    {
        List<(string Name, JsonObject Schema)> members = [];
        foreach (var (name, node) in (JsonObject)schema["properties"]!)
        {
            if (node is JsonObject member)
            {
                members.Add((name, member));
            }
        }

        return members;
    }

    // Writes a keyed object as the single member its key example names, so that the shape a reader has to
    // copy — a member name carrying data — is visible rather than described.
    private static void WriteKeyedObject(
        StringBuilder text,
        JsonObject schema,
        JsonObject propertyNames,
        JsonObject root,
        string path,
        int depth)
    {
        var key = (propertyNames["examples"] as JsonArray)?.FirstOrDefault()?.GetValue<string>()
            ?? throw new InvalidOperationException(
                $"The keyed object '{path}' states no example member name. Annotate the key property of its "
                + "element type with [JsonSchemaExample].");
        var valueSchema = schema["additionalProperties"] as JsonObject
            ?? throw new InvalidOperationException($"The keyed object '{path}' declares no value schema.");

        _ = text.Append("{\n");
        WriteDescription(text, valueSchema, depth + 1);
        _ = text.Append(Indentation(depth + 1)).Append(FormatString(key)).Append(": ");
        WriteValue(text, valueSchema, root, Extend(path, key), depth + 1);
        _ = text.Append(",\n").Append(Indentation(depth)).Append('}');
    }

    // The last resort: a container with nothing to show still has a shape to show. Anything else is a setting
    // whose value the schema cannot supply, which is a missing annotation on the model.
    private static string EmptyContainer(JsonObject schema, string path)
        => schema["type"]?.GetValue<string>() switch
        {
            "array" => "[]",
            "object" => "{}",
            _ => throw new InvalidOperationException(
                $"The setting '{path}' states neither an example nor a default, and is not a container. "
                + "Annotate the model property with [JsonSchemaExample]."),
        };

    // A value stays on one line however long it is, the $schema URL included: wrapping it would put JSON on a
    // continuation line, where an editor and a reader would have to reassemble it.
    private static string FormatValue(JsonNode? value)
        => value switch
        {
            null => "null",
            JsonArray items => "[" + string.Join(", ", items.Select(FormatValue)) + "]",
            JsonObject members => "{" + string.Join(", ", members.Select(FormatMember)) + "}",
            _ => value.ToJsonString(ValueOptions),
        };

    private static string FormatMember(KeyValuePair<string, JsonNode?> member)
        => FormatString(member.Key) + ": " + FormatValue(member.Value);

    private static string FormatString(string value) => JsonValue.Create(value).ToJsonString(ValueOptions);

    private static string Extend(string path, string name) => path.Length == 0 ? name : path + "." + name;

    private static string Indentation(int depth)
        => string.Concat(Enumerable.Repeat(IndentUnit, depth));
}
