// Copyright (C) Tenacom and Contributors. Licensed under the MIT license.
// See the LICENSE file in the project root for full license information.

using System.Text;
using Microsoft.CodeAnalysis;

namespace Buildvana.Sdk.SourceGenerators.Internal;

/// <summary>
/// Provides extension methods for <see cref="StringBuilder"/>.
/// </summary>
internal static class StringBuilderExtensions
{
    extension(StringBuilder @this)
    {
        public StringBuilder AppendAutoGenerated()
            => @this.AppendLine("// <auto-generated/>");

        public StringBuilder AppendBooleanAssemblyAttribute(string name, bool? value)
            => value is bool flag
                ? @this.AppendLine($"[assembly:{name}({(flag ? "true" : "false")})]")
                : @this;
    }
}
