// Copyright (C) Tenacom and Contributors. Licensed under the MIT license.
// See the LICENSE file in the project root for full license information.

using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;

namespace Buildvana.Core.Dependencies;

/// <summary>
/// The source-generated serializer context for the pin dump files Buildvana SDK writes and <c>bv</c> reads.
/// </summary>
/// <remarks>
/// <para>Both ends of the exchange use this context, so a dump is written and read by one description of its
/// shape. Absent metadata is omitted rather than written as <see langword="null"/>, which keeps a dump of a
/// large solution to what it actually states.</para>
/// <para>Reading is strict about unknown members: a dump is written by the very SDK the tool checked before
/// running, so a member the tool does not know means the two disagree about the contract.</para>
/// </remarks>
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    RespectNullableAnnotations = true,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow,
    WriteIndented = true)]
[JsonSerializable(typeof(PackagePinDump))]
[SuppressMessage(
    "ApiDesign",
    "RS0041:Public members should not use oblivious types",
    Justification = "Generated by the System.Text.Json source generator; oblivious by construction.")]
public sealed partial class PackagePinDumpJsonContext : JsonSerializerContext;
