// Copyright (C) Tenacom and Contributors. Licensed under the MIT license.
// See the LICENSE file in the project root for full license information.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security;
using System.Text;
using Buildvana.Core;
using Buildvana.Core.ConsoleOutput;
using Buildvana.Core.Diagnostics;
using Buildvana.Core.HomeDirectory;
using CommunityToolkit.Diagnostics;

namespace Buildvana.Tool.Services.Dependencies;

/// <summary>
/// Writes the transitive override files, and removes the ones a run leaves with nothing to say.
/// </summary>
/// <remarks>
/// <para>The files are bv's own. Nothing reads them back to decide anything, they are rewritten whole at
/// every apply run, and their header says as much to whoever opens one.</para>
/// <para>A file whose content is already what the run would write is left alone, timestamp included. A
/// rewritten file invalidates the restore that follows it, and a run that changed nothing must not make work
/// for the next build.</para>
/// </remarks>
internal sealed class SidecarWriter(IHomeDirectoryProvider home, IReporter reporter)
{
    private const string CentralPurpose = """
                                            These package versions lift transitive dependencies out of versions covered by a security
                                            advisory. They reach the projects that manage their package versions centrally, and cover only
                                            packages the repository does not pin itself.
                                          """;

    private const string ProjectPurpose = """
                                            Each reference below promotes a transitive dependency to a direct reference of this project, so
                                            that the project stops resolving a version covered by a security advisory. PrivateAssets="all"
                                            keeps the promotions out of the package this project produces: its stated dependencies are the
                                            ones it would state without this file.
                                          """;

    /// <summary>
    /// Writes what a plan states, in the central file and in one file per project.
    /// </summary>
    /// <param name="plan">What the files are to hold.</param>
    /// <returns><see langword="true"/> if any file was written or removed, <see langword="false"/> if the
    /// files on disk already stated exactly this. The lifecycle reads the answer as the whole question of
    /// whether the graph it last read is still the current one.</returns>
    /// <exception cref="BuildFailedException">A file could not be written or removed.</exception>
    public bool Write(TransitiveOverridePlan plan)
    {
        Guard.IsNotNull(plan);
        var central = plan.Central.Count == 0 ? null : Compose(CentralPurpose, plan.Central, CentralItem);
        var changed = WriteOrRemove(home.GetFullPath(TransitiveOverrides.CentralFileName), central);
        foreach (var project in plan.Projects)
        {
            var content = project.Promotions.Count == 0 ? null : Compose(ProjectPurpose, project.Promotions, ProjectItem);
            changed |= WriteOrRemove(TransitiveOverrides.ProjectFilePath(project.ProjectFullPath), content);
        }

        return changed;
    }

    // Entries are ordered by id, and lines end the same way on either platform, so that two runs finding the
    // same vulnerabilities write the same bytes. A file whose bytes change is a file a reviewer has to read.
    private static string Compose(string purpose, IReadOnlyList<PackageOverride> entries, Func<PackageOverride, string> item)
    {
        var items = string.Join(
            "\n",
            entries.OrderBy(static entry => entry.PackageId, StringComparer.OrdinalIgnoreCase).Select(item));

        return ComposeLines(purpose, items).ReplaceLineEndings("\n");
    }

    private static string ComposeLines(string purpose, string items)
        => $"""
                <Project>

                  <!--
                    Generated by `bv dependencies`. Do not edit: the next run rewrites this file whole.

                {purpose}
                  -->

                  <ItemGroup>
                {items}
                  </ItemGroup>

                </Project>

                """;

    private static string CentralItem(PackageOverride entry)
        => $"""    <PackageVersion Include="{Escape(entry.PackageId)}" Version="{Escape(entry.Version!.ToNormalizedString())}" />""";

    private static string ProjectItem(PackageOverride entry)
    {
        var version = entry.Version is null ? string.Empty : $" Version=\"{Escape(entry.Version.ToNormalizedString())}\"";
        return $"""    <PackageReference Include="{Escape(entry.PackageId)}"{version} PrivateAssets="all" />""";
    }

    private static string Escape(string value) => SecurityElement.Escape(value) ?? value;

    private bool WriteOrRemove(string path, string? content)
    {
        try
        {
            return content is null ? RemoveFile(path) : WriteFile(path, content);
        }
        catch (Exception exception) when (exception.IsIORelatedException)
        {
            throw new BuildFailedException($"Could not write '{Name(path)}': {exception.Message}", exception);
        }
    }

    private bool RemoveFile(string path)
    {
        if (!File.Exists(path))
        {
            return false;
        }

        File.Delete(path);
        reporter.Detail($"Removed {Name(path)}, which has nothing left to state.");
        return true;
    }

    private bool WriteFile(string path, string content)
    {
        if (File.Exists(path) && string.Equals(File.ReadAllText(path), content, StringComparison.Ordinal))
        {
            return false;
        }

        File.WriteAllText(path, content, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        reporter.Detail($"Wrote {Name(path)}.");
        return true;
    }

    private string Name(string path) => home.TryGetRelativePath(path, out var relative) ? relative : path;
}
