// <auto-generated/>
// Copyright (C) Tenacom and Contributors. Licensed under the MIT license.
// See the LICENSE file in the project root for full license information.
//
// Shipped with Buildvana SDK and injected into the compilation of hooks (file-based apps under
// .buildvana/hooks/). Not compiled as part of Buildvana itself. The auto-generated marker exempts
// this file from the analyzers active in the consuming repository.

#nullable enable

using System;
using System.IO;
using System.Linq;
using System.Text.Json;

/// <summary>
/// Loads the repository's Buildvana configuration file for use by hooks.
/// </summary>
internal static class BvConfig
{
    private static readonly JsonDocumentOptions DocumentOptions = new()
    {
        CommentHandling = JsonCommentHandling.Skip,
        AllowTrailingCommas = true,
    };

    /// <summary>
    /// Loads the Buildvana configuration, probing the four well-known candidates
    /// (<c>buildvana.json</c>, <c>buildvana.jsonc</c>, and the same names under <c>.buildvana/</c>)
    /// relative to <paramref name="homeDirectory"/>.
    /// </summary>
    /// <param name="homeDirectory">The home directory to probe; the current directory when omitted
    /// (hooks run from the home directory).</param>
    /// <returns>The root element of the configuration, or an empty JSON object when no configuration
    /// file exists.</returns>
    /// <exception cref="InvalidOperationException">More than one configuration file exists.</exception>
    public static JsonElement Load(string? homeDirectory = null)
    {
        var baseDirectory = string.IsNullOrEmpty(homeDirectory) ? Directory.GetCurrentDirectory() : homeDirectory;
        string[] candidates =
        [
            Path.Combine(baseDirectory, "buildvana.json"),
            Path.Combine(baseDirectory, "buildvana.jsonc"),
            Path.Combine(baseDirectory, ".buildvana", "buildvana.json"),
            Path.Combine(baseDirectory, ".buildvana", "buildvana.jsonc"),
        ];
        var existing = candidates.Where(File.Exists).ToArray();
        if (existing.Length > 1)
        {
            throw new InvalidOperationException($"Multiple Buildvana configuration files found: {string.Join(", ", existing)}. Keep only one.");
        }

        var json = existing.Length == 0 ? "{}" : File.ReadAllText(existing[0]);
        using var document = JsonDocument.Parse(json, DocumentOptions);
        return document.RootElement.Clone();
    }
}
