// <auto-generated/>
// Copyright (C) Tenacom and Contributors. Licensed under the MIT license.
// See the LICENSE file in the project root for full license information.
//
// Shipped with Buildvana SDK and injected into the compilation of hooks (file-based apps under
// .buildvana/hooks/). Not compiled as part of Buildvana itself. The auto-generated marker exempts
// this file from the analyzers active in the consuming repository.

#nullable enable

using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;

/// <summary>
/// The context handed to a <c>release</c> hook by bv, deserialized from the JSON file whose absolute
/// path is published in the <c>BV_HOOK_CONTEXT</c> environment variable.
/// </summary>
/// <remarks>
/// <para>The contract is additive-only: newer bv versions may add properties, never remove or
/// repurpose existing ones. Properties missing from the file (written by an older bv) keep their
/// default values.</para>
/// <para>The context is parsed by hand rather than deserialized: file-based apps run with
/// reflection-based JSON serialization disabled, and hand-parsing also gives the additive
/// tolerance above by construction.</para>
/// </remarks>
internal sealed record BvHookContext
{
    /// <summary>
    /// The name of the environment variable holding the absolute path of the context file.
    /// </summary>
    public const string EnvironmentVariable = "BV_HOOK_CONTEXT";

    /// <summary>
    /// Gets the absolute path of the home directory. This is also the working directory of the hook.
    /// </summary>
    public string HomeDirectory { get; init; } = string.Empty;

    /// <summary>
    /// Gets the version being released, in simple <c>MAJOR.MINOR.PATCH</c> form, without any prerelease tag.
    /// </summary>
    public string ReleaseVersion { get; init; } = string.Empty;

    /// <summary>
    /// Gets the version being released, in full semantic version form: <see cref="ReleaseVersion"/>, plus
    /// <c>-tag</c> when the version is a prerelease. This is the form used by release tags and embedded
    /// in artifact names.
    /// </summary>
    public string ReleaseSemVer { get; init; } = string.Empty;

    /// <summary>
    /// Gets the previously released version (the latest release tag reachable from <c>HEAD</c>),
    /// or <see langword="null"/> when no previous release exists.
    /// </summary>
    public string? PreviousVersion { get; init; }

    /// <summary>
    /// Gets a value indicating whether the version being released is a prerelease.
    /// </summary>
    public bool IsPrerelease { get; init; }

    /// <summary>
    /// Gets a value indicating whether the release is a public release.
    /// </summary>
    public bool IsPublicRelease { get; init; }

    /// <summary>
    /// Gets the absolute path of the directory containing the build artifacts.
    /// </summary>
    public string ArtifactsDirectory { get; init; } = string.Empty;

    /// <summary>
    /// Gets the packages produced by the release, as a map from package ID to version.
    /// </summary>
    public IReadOnlyDictionary<string, string> ProducedPackages { get; init; }
        = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

    /// <summary>
    /// Gets a value indicating whether the built-in self-reference rewrites ran in this release.
    /// </summary>
    public bool Dogfooded { get; init; }

    /// <summary>
    /// Loads the context of the current hook run.
    /// </summary>
    /// <returns>The deserialized hook context.</returns>
    /// <exception cref="InvalidOperationException">
    /// The <c>BV_HOOK_CONTEXT</c> environment variable is not set (the program is not running as a hook),
    /// or the context file does not contain a JSON object.
    /// </exception>
    public static BvHookContext Load()
    {
        var path = Environment.GetEnvironmentVariable(EnvironmentVariable);
        if (string.IsNullOrEmpty(path))
        {
            throw new InvalidOperationException($"{EnvironmentVariable} is not set; this program must be run by bv as a hook.");
        }

        using var document = JsonDocument.Parse(File.ReadAllText(path));
        var root = document.RootElement;
        if (root.ValueKind != JsonValueKind.Object)
        {
            throw new InvalidOperationException($"The hook context file '{path}' does not contain a JSON object.");
        }

        return new BvHookContext
        {
            HomeDirectory = GetString(root, "homeDirectory") ?? string.Empty,
            ReleaseVersion = GetString(root, "releaseVersion") ?? string.Empty,
            ReleaseSemVer = GetString(root, "releaseSemVer") ?? string.Empty,
            PreviousVersion = GetString(root, "previousVersion"),
            IsPrerelease = GetBoolean(root, "isPrerelease"),
            IsPublicRelease = GetBoolean(root, "isPublicRelease"),
            ArtifactsDirectory = GetString(root, "artifactsDirectory") ?? string.Empty,
            ProducedPackages = GetStringMap(root, "producedPackages"),
            Dogfooded = GetBoolean(root, "dogfooded"),
        };
    }

    private static string? GetString(JsonElement element, string propertyName)
        => element.TryGetProperty(propertyName, out var value) && value.ValueKind == JsonValueKind.String
            ? value.GetString()
            : null;

    private static bool GetBoolean(JsonElement element, string propertyName)
        => element.TryGetProperty(propertyName, out var value) && value.ValueKind == JsonValueKind.True;

    private static IReadOnlyDictionary<string, string> GetStringMap(JsonElement element, string propertyName)
    {
        var result = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        if (element.TryGetProperty(propertyName, out var value) && value.ValueKind == JsonValueKind.Object)
        {
            foreach (var property in value.EnumerateObject())
            {
                if (property.Value.ValueKind == JsonValueKind.String)
                {
                    result[property.Name] = property.Value.GetString()!;
                }
            }
        }

        return result;
    }
}
